name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_AGENCIES={total_agencies}
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini
